[package]
name = "embertune"
version = "0.1.0"
description = "A local music player with smart library tools"
authors = ["you"]
edition = "2021"

[lib]
name = "embertune_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.2"
tauri-plugin-single-instance = "2"
tokio = { version = "1.53.1", features = ["macros", "process", "rt-multi-thread", "sync", "time", "io-util"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
dirs = "6.0.0"
ureq = { version = "2", features = ["json"] }
base64 = "0.22"

